work_dir: ./work_dir/ntu60_EAP/xsub/OBR100/_SoR_Fixed_OBR100

phase: train
debug: False
ob_ratio: 100
backbone: True
# processor
processor: processor.processor.Processor
# feeder
feeder: feeders.feeder_FixedOBR.Feeder
train_feeder_args:

  data_path:
    [
      ./data/NTU-RGB-D/xsub/train/train_100_data_joint.npy
    ]
  label_path: ./data/NTU-RGB-D/xsub/train/train_label.pkl

test_feeder_args:
  data_path:
    [
      ./data/NTU-RGB-D/xsub/val/val_100_data_joint.npy
    ]
  label_path: ./data/NTU-RGB-D/xsub/val/val_label.pkl

data_frame: 100
# model
model:
  encoder: model.SoRgcn.Model
  dcls: model.d_cls_single.class_discriminator
encoder_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

dcls_args:
  num_class: 60

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [ 35,55,65 ]
warm_up_epoch: 5

# training
device: [ 2,3 ]
batch_size: 64
test_batch_size: 64
num_epoch: 70
nesterov: True
save_interval: 5
eval_interval: 10
data_random_ob: False
Detailed_test_epoch: 35

#data processing
train_fill_type: zero
test_fill_type: zero
